on: [push]
#when you leave this empty without specifying branch, It will trigger *any* push. 

jobs:
  hello_world_job:
    runs-on: ubuntu-latest #This is the CI server or runner.. It has the same meaning 
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3 # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory, In this case it uses the file "action.yaml". 
        id: hello
        with:
          who-to-greet: 'Naor Yamin' # change it to your name
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"